/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Sales;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import model.Business.Business;
import model.CustomerManagement.CustomerProfile;
import model.OrderManagement.Order;
import model.ProductManagement.ProductCatalog;
import model.SalesManagement.SalesPersonProfile;
import ui.Admin.PerformanceReportJPanel;

/**
 *
 * @author nikha
 */
public class SalesWorkAreaJPanel extends javax.swing.JPanel {

    Business business;
    SalesPersonProfile spp;
    JPanel cardSequencePanel;
    JButton btnLogin;
    private ArrayList<Order> orders;
    private ProductCatalog combinedProductCatalog;

    /**
     * Creates new form ManageCustomer
     */
    public SalesWorkAreaJPanel(Business business, SalesPersonProfile spp, JPanel cardSequencePanel,
            JButton btnLogin) {
        initComponents();
        this.business = business;
        this.spp = spp;
        this.cardSequencePanel = cardSequencePanel;
        this.btnLogin = btnLogin;

        lblTitle.setBackground(new Color(153, 153, 255));
        lblTitle.setOpaque(true);
        Border border = new LineBorder(Color.GRAY, 2, true);
        lblTitle.setBorder(border);

        orders = business.getMasterOrderList().getOrders();
        combinedProductCatalog = business.getProductCatalog();
        btnLogin.setVisible(true);
        btnLogin.setText("LOGOUT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomer = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnServeCustomer = new javax.swing.JButton();
        btnRevComission = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        btnProductReview = new javax.swing.JButton();

        lblCustomer.setText("Customer:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SALES WORK AREA");

        btnServeCustomer.setBackground(new java.awt.Color(153, 153, 255));
        btnServeCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnServeCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomer.setText("Serve Customer");
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerActionPerformed(evt);
            }
        });

        btnRevComission.setBackground(new java.awt.Color(153, 153, 255));
        btnRevComission.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRevComission.setForeground(new java.awt.Color(255, 255, 255));
        btnRevComission.setText("Update Products");
        btnRevComission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevComissionActionPerformed(evt);
            }
        });

        btnPerformanceReports.setBackground(new java.awt.Color(153, 153, 255));
        btnPerformanceReports.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        btnProductReview.setBackground(new java.awt.Color(153, 153, 255));
        btnProductReview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProductReview.setForeground(new java.awt.Color(255, 255, 255));
        btnProductReview.setText("Product Review");
        btnProductReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnServeCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProductReview, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnRevComission)
                        .addGap(40, 40, 40)
                        .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServeCustomer))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductReview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRevComission, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(374, 374, 374))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerActionPerformed
        // TODO add your handling code here:
        String customerName = txtCustomer.getText();
        if (customerName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "PLEASE ENTER A CUSTOMER NAME!");
            return;
        }

        CustomerProfile selectedCustomer = business.getCustomerDirectory().findCustomer(customerName);
        if (selectedCustomer == null) {
            JOptionPane.showMessageDialog(this, "CUSTOMER DOES NOT EXIST!");
            return;
        }
        ProcessOrderJPanel panel = new ProcessOrderJPanel(cardSequencePanel, business, selectedCustomer, spp);
        cardSequencePanel.add("ProcessOrderJPanel", panel);
        CardLayout cardLayout = new CardLayout();
        cardSequencePanel.setLayout(cardLayout);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_btnServeCustomerActionPerformed

    private void btnRevComissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevComissionActionPerformed
        // TODO add your handling code here:
        UpdateProductPrices panel = new UpdateProductPrices(cardSequencePanel, business, spp);
        cardSequencePanel.add("UpdatedProductPrices", panel);
        CardLayout cardLayout = new CardLayout();
        cardSequencePanel.setLayout(cardLayout);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_btnRevComissionActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:
        PerformanceReportJPanel panel = new PerformanceReportJPanel(cardSequencePanel, business, spp, orders, combinedProductCatalog);
        cardSequencePanel.add("PerformanceReportJPanel", panel);
        CardLayout cardLayout = new CardLayout();
        cardSequencePanel.setLayout(cardLayout);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_btnPerformanceReportsActionPerformed

    private void btnProductReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductReviewActionPerformed
        // TODO add your handling code here:
        ProductReviewJPanel panel = new ProductReviewJPanel(cardSequencePanel, business, spp);
        cardSequencePanel.add("ProductReviewJPanel", panel);
        CardLayout cardLayout = new CardLayout();
        cardSequencePanel.setLayout(cardLayout);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.next(cardSequencePanel);
    }//GEN-LAST:event_btnProductReviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnProductReview;
    private javax.swing.JButton btnRevComission;
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCustomer;
    // End of variables declaration//GEN-END:variables
}
