/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import model.AdminManagement.AdminProfile;
import model.Business.Business;
import model.OrderManagement.Order;
import model.ProductManagement.ProductCatalog;
import model.Supplier.Supplier;

/**
 *
 * @author nikha
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private ArrayList<Order> orders;
    JButton btnLogin;
    JPanel cardSequencePanel;
    Business business;
    AdminProfile admin;
    ProductCatalog productCatalog;
    Supplier selectedSupplier;
    

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(Business business, AdminProfile admin, JPanel cardSequencePanel, JButton btnLogin) {
       initComponents();
        
        this.cardSequencePanel = cardSequencePanel;
        this.business = business;
        this.admin = admin;
        this.orders = business.getMasterOrderList().getOrders();
        this.btnLogin = btnLogin;
        this.productCatalog = productCatalog;
        
        //lblTitle.setBackground(new Color(153, 153, 255));
        lblTitle.setOpaque(true);
        Border border = new LineBorder(Color.GRAY,2,true);
        lblTitle.setBorder(border);
        
        btnLogin.setVisible(true);
        btnLogin.setText("LOGOUT");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageSupplier = new javax.swing.JButton();
        btnManageCustomer = new javax.swing.JButton();
        btnPerformanceRepots = new javax.swing.JButton();

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("       ADMIN WORK SPACE");

        btnManageSupplier.setBackground(new java.awt.Color(0, 0, 0));
        btnManageSupplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnManageSupplier.setText("Supplier Management");
        btnManageSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSupplierActionPerformed(evt);
            }
        });

        btnManageCustomer.setBackground(new java.awt.Color(0, 0, 0));
        btnManageCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCustomer.setText("Customer Management");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        btnPerformanceRepots.setBackground(new java.awt.Color(0, 0, 0));
        btnPerformanceRepots.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPerformanceRepots.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceRepots.setText("Performance Reports");
        btnPerformanceRepots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceRepotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnManageCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnPerformanceRepots)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceRepots, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(467, 467, 467))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSupplierActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        AdminManageSupplierJPanel iet = new AdminManageSupplierJPanel(business , cardSequencePanel, 
                admin, btnLogin);
       
        cardSequencePanel.add("FindResourceAsset", iet);
        ((java.awt.CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);

    }//GEN-LAST:event_btnManageSupplierActionPerformed

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        // TODO add your handling code here:
         ManageCustomersJPanel mcjp = new ManageCustomersJPanel(cardSequencePanel, business, admin, btnLogin);
       
        cardSequencePanel.add("ManageCustomersJPanel", mcjp);
        ((java.awt.CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);

    }//GEN-LAST:event_btnManageCustomerActionPerformed

    private void btnPerformanceRepotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceRepotsActionPerformed
        // TODO add your handling code here:
        PerformanceReportJPanel prp = new PerformanceReportJPanel(cardSequencePanel, business, 
                admin, orders, productCatalog, btnLogin);
        
        cardSequencePanel.add("egfw ", prp);
        ((java.awt.CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);

    }//GEN-LAST:event_btnPerformanceRepotsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageSupplier;
    private javax.swing.JButton btnPerformanceRepots;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
