/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MarketingWorkAreaJPanel;

/**
 *
 * @author nikha
 */
public class MarketingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarketingWorkAreaJPanel
     */
    public MarketingWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageMarkets = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnPerformanceReports = new javax.swing.JButton();
        btnManageChannels = new javax.swing.JButton();
        btnManagePrices1 = new javax.swing.JButton();

        btnManageMarkets.setBackground(new java.awt.Color(153, 153, 255));
        btnManageMarkets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageMarkets.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMarkets.setText("Manage Markets");
        btnManageMarkets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketsActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(153, 153, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MARKETING WORK SPACE");
        lblTitle.setOpaque(true);

        btnPerformanceReports.setBackground(new java.awt.Color(153, 153, 255));
        btnPerformanceReports.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        btnManageChannels.setBackground(new java.awt.Color(153, 153, 255));
        btnManageChannels.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageChannels.setForeground(new java.awt.Color(255, 255, 255));
        btnManageChannels.setText("Manage Channels");
        btnManageChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageChannelsActionPerformed(evt);
            }
        });

        btnManagePrices1.setBackground(new java.awt.Color(153, 153, 255));
        btnManagePrices1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManagePrices1.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePrices1.setText("Manage Prices");
        btnManagePrices1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePrices1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnManageChannels, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnManageMarkets, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManagePrices1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageMarkets, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManagePrices1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMarketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketsActionPerformed
        // TODO add your handling code here:

        //        ManageTheBusinessJPanel aos = new ManageTheBusinessJPanel(business, cardSequencePanel);

        //        cardSequencePanel.add("ManageVulns", aos);
        //        ((java.awt.CardLayout) cardSequencePanel.getLayout()).next(cardSequencePanel);
    }//GEN-LAST:event_btnManageMarketsActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:

        //        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
        //        CardSequencePanel.add("RiskAgendaObjectives", aos);

    }//GEN-LAST:event_btnPerformanceReportsActionPerformed

    private void btnManageChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageChannelsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnManageChannelsActionPerformed

    private void btnManagePrices1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePrices1ActionPerformed
        // TODO add your handling code here:

        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);

        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
    }//GEN-LAST:event_btnManagePrices1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageChannels;
    private javax.swing.JButton btnManageMarkets;
    private javax.swing.JButton btnManagePrices1;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
